title: Using events to trigger JavaScript code
hero_image: images/banner.png
description: Using events to trigger JavaScript code
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Using Events in JavaScript
