---
title: Events gebruiken om JavaScript-code te activeren
hero_image: images/banner.png
description: Events gebruiken om JavaScript-code te activeren
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Events in JavaScript gebruiken
